name = "GBrwnn"
uuid = "b9b5926f-d9f2-4c41-9028-4bb94193468c"
authors = ["Søren B. Vilsen <svilsen@math.aau.dk>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
